spring.application.name=gestionVentesBackend
# ----------------------------------------------------
# Configuration de la Base de Donn�es MySQL (XAMPP)
# ----------------------------------------------------np
# Remplacez 'gestionvente' par le nom de votre base de donn�es
spring.datasource.url=jdbc:mysql://localhost:3307/gestionvente
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ----------------------------------------------------
# Configuration de JPA/Hibernate
# ----------------------------------------------------
# 'update' permet � Hibernate de modifier le sch�ma de la base de donn�es
# en fonction de vos classes @Entity. Utile en d�veloppement.
# Utilisez 'none' ou 'validate' en production.
spring.jpa.hibernate.ddl-auto=update

# Affiche les requ�tes SQL g�n�r�es par Hibernate (pour le d�bogage)
spring.jpa.show-sql=true

# Sp�cifiez le dialecte MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ----------------------------------------------------
# Configuration du serveur Spring Boot
# ----------------------------------------------------
server.port=9090